In [1]:
import pandas as pd
from pathlib import Path

DATA = Path('../data')

## HPC HNO — Cluster column

In [2]:
hno_2024 = pd.read_csv(DATA / 'hpc_hno_2024.csv', skiprows=[1])  # skip HXL tag row
hno_2025 = pd.read_csv(DATA / 'hpc_hno_2025.csv', skiprows=[1])
hno_2026 = pd.read_csv(DATA / 'hpc_hno_2026.csv')

hno_clusters = (
    pd.concat([
        hno_2024[['Cluster']].assign(source='hpc_hno_2024'),
        hno_2025[['Cluster']].assign(source='hpc_hno_2025'),
        hno_2026[['Cluster']].assign(source='hpc_hno_2026'),
    ])
    .dropna(subset=['Cluster'])
    .groupby('Cluster')['source'].apply(lambda s: ', '.join(sorted(s.unique())))
    .reset_index()
    .rename(columns={'source': 'present_in'})
    .sort_values('Cluster')
    .reset_index(drop=True)
)

print(f'{len(hno_clusters)} unique clusters across HNO 2024/2025/2026')
hno_clusters

/tmp/ipykernel_150848/1507177348.py:1: DtypeWarning: Columns (0: Admin 1 PCode, 1: Admin 1 Name, 2: Admin 2 PCode, 3: Admin 2 Name, 4: Admin 3 PCode, 5: Admin 3 Name, 6: Info) have mixed types. Specify dtype option on import or set low_memory=False.
  hno_2024 = pd.read_csv(DATA / 'hpc_hno_2024.csv', skiprows=[1])  # skip HXL tag row

/tmp/ipykernel_150848/1507177348.py:2: DtypeWarning: Columns (0: Admin 1 PCode, 1: Admin 1 Name, 2: Admin 3 PCode, 3: Admin 3 Name, 4: Info) have mixed types. Specify dtype option on import or set low_memory=False.
  hno_2025 = pd.read_csv(DATA / 'hpc_hno_2025.csv', skiprows=[1])

20 unique clusters across HNO 2024/2025/2026

    Cluster                                present_in
0       AGR                              hpc_hno_2024
1       ALL  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
2       CCM  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
3       CSS                hpc_hno_2024, hpc_hno_2025
4       EDU  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
5       ERY                hpc_hno_2024, hpc_hno_2025
6       FSC  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
7       HEA  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
8       LOG                hpc_hno_2024, hpc_hno_2025
9       MPC                hpc_hno_2025, hpc_hno_2026
10       MS  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
11      NUT  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
12      PRO  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
13  PRO-CPN  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
14  PRO-GBV  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
15  PRO-HLP  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
16  PRO-MIN  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
17      SHL  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026
18      TEL                              hpc_hno_2025
19      WSH  hpc_hno_2024, hpc_hno_2025, hpc_hno_2026

## FTS Requirements — cluster & globalcluster

In [3]:
fts_globalcluster = pd.read_csv(DATA / 'fts_requirements_funding_globalcluster_global.csv')

fts_clusters = (
    pd.concat([
        fts_globalcluster[['cluster']].assign(source='fts_globalcluster'),
    ])
    .dropna(subset=['cluster'])
    .drop_duplicates(subset=['cluster'])
    .reset_index()
    .sort_values('cluster')
    .reset_index(drop=True)
)

print(f'{len(fts_clusters)} unique clusters in FTS requirements')
fts_clusters

24 unique clusters in FTS requirements

    index                                     cluster             source
0      14                                 Agriculture  fts_globalcluster
1     121                                    COVID-19  fts_globalcluster
2     656              Camp Coordination / Management  fts_globalcluster
3       0           Coordination and support services  fts_globalcluster
4      16                              Early Recovery  fts_globalcluster
5       1                                   Education  fts_globalcluster
6       2                   Emergency Shelter and NFI  fts_globalcluster
7     246                Emergency Telecommunications  fts_globalcluster
8       3                               Food Security  fts_globalcluster
9       4                                      Health  fts_globalcluster
10      5                                   Logistics  fts_globalcluster
11      6                                Multi-sector  fts_globalcluster
12     13          Multiple clusters/sectors (shared)  fts_globalcluster
13      7                           Multipurpose Cash  fts_globalcluster
14     12                               Not specified  fts_globalcluster
15      8                                   Nutrition  fts_globalcluster
16     25                                       Other  fts_globalcluster
17      9                                  Protection  fts_globalcluster
18     27               Protection - Child Protection  fts_globalcluster
19     28          Protection - Gender-Based Violence  fts_globalcluster
20     29     Protection - Housing, Land and Property  fts_globalcluster
21   1648  Protection - Human Trafficking & Smuggling  fts_globalcluster
22     10                    Protection - Mine Action  fts_globalcluster
23     11                    Water Sanitation Hygiene  fts_globalcluster

## Project Summary — Cluster column

In [4]:
projects = pd.read_csv(DATA / 'ProjectSummaryWithLocationAndCluster20260418111139715.csv')

project_clusters = (
    projects['Cluster']
    .dropna()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
    .to_frame()
)

print(f'{len(project_clusters)} unique clusters in Project Summary')
project_clusters

21 unique clusters in Project Summary

                                 Cluster
0       COORDINATION AND COMMON SERVICES
1      Coordination and Support Services
2                              EDUCATION
3   EMERGENCY SHELTER AND NON-FOOD ITEMS
4                              Education
5              Emergency Shelter and NFI
6          FOOD SECURITY AND AGRICULTURE
7                          Food Security
8                                 HEALTH
9                                 Health
10                    Multi-Purpose Cash
11                          Multi-Sector
12                             NUTRITION
13                             Nutrition
14                            PROTECTION
15                            Protection
16                     Protection - CPiE
17                      Protection - GBV
18                      Protection - HLP
19         WATER, SANITATION AND HYGIENE
20         Water, Sanitation and Hygiene

## Cross-file cluster overlap

## HNO code → FTS globalcluster mapping

In [5]:
HNO_TO_FTS = {
    'AGR':     'Agriculture',
    'ALL':     None,  # cross-cutting / all clusters
    'CCM':     'Camp Coordination / Management',
    'CSS':     'Coordination and support services',
    'EDU':     'Education',
    'ERY':     'Early Recovery',
    'FSC':     'Food Security',
    'HEA':     'Health',
    'LOG':     'Logistics',
    'MPC':     'Multipurpose Cash',
    'MS':      'Multi-sector',
    'NUT':     'Nutrition',
    'PRO':     'Protection',
    'PRO-CPN': 'Protection - Child Protection',
    'PRO-GBV': 'Protection - Gender-Based Violence',
    'PRO-HLP': 'Protection - Housing, Land and Property',
    'PRO-MIN': 'Protection - Mine Action',
    'SHL':     'Emergency Shelter and NFI',
    'TEL':     'Emergency Telecommunications',
    'WSH':     'Water Sanitation Hygiene',
}

mapping_df = (
    pd.DataFrame.from_dict(HNO_TO_FTS, orient='index', columns=['fts_globalcluster'])
    .rename_axis('hno_code')
    .reset_index()
    .sort_values('hno_code')
    .reset_index(drop=True)
)

fts_names = set(fts_clusters['cluster'])
mapping_df['fts_match'] = mapping_df['fts_globalcluster'].apply(
    lambda x: x in fts_names if x else None
)

print(f"Codes with no FTS match: {mapping_df[mapping_df['fts_match'] == False]['hno_code'].tolist()}")
mapping_df

Codes with no FTS match: ['ALL']

   hno_code                        fts_globalcluster  fts_match
0       AGR                              Agriculture       True
1       ALL                                      NaN      False
2       CCM           Camp Coordination / Management       True
3       CSS        Coordination and support services       True
4       EDU                                Education       True
5       ERY                           Early Recovery       True
6       FSC                            Food Security       True
7       HEA                                   Health       True
8       LOG                                Logistics       True
9       MPC                        Multipurpose Cash       True
10       MS                             Multi-sector       True
11      NUT                                Nutrition       True
12      PRO                               Protection       True
13  PRO-CPN            Protection - Child Protection       True
14  PRO-GBV       Protection - Gender-Based Violence       True
15  PRO-HLP  Protection - Housing, Land and Property       True
16  PRO-MIN                 Protection - Mine Action       True
17      SHL                Emergency Shelter and NFI       True
18      TEL             Emergency Telecommunications       True
19      WSH                 Water Sanitation Hygiene       True

In [6]:
fts_names = set(fts_clusters['cluster'])
hno_mapped = {HNO_TO_FTS[c] for c in hno_clusters['Cluster'] if HNO_TO_FTS.get(c)}
project_names = set(project_clusters['Cluster'])

all_clusters = sorted(fts_names | hno_mapped | project_names)

overlap = pd.DataFrame({
    'fts_globalcluster': all_clusters,
    'in_hno': [c in hno_mapped for c in all_clusters],
    'in_fts': [c in fts_names for c in all_clusters],
    'in_projects': [c in project_names for c in all_clusters],
})
overlap['hno_code'] = overlap['fts_globalcluster'].map({v: k for k, v in HNO_TO_FTS.items() if v})
overlap['count'] = overlap[['in_hno', 'in_fts', 'in_projects']].sum(axis=1)
overlap = overlap.sort_values(['count', 'fts_globalcluster'], ascending=[False, True]).reset_index(drop=True)

print(f'{len(overlap)} unique clusters total (normalized to FTS globalcluster names)')
overlap

39 unique clusters total (normalized to FTS globalcluster names)

,fts_globalcluster,in_hno,in_fts,in_projects,hno_code,count
0,Education,True,True,True,EDU,3
1,Emergency Shelter and NFI,True,True,True,SHL,3
2,Food Security,True,True,True,FSC,3
3,Health,True,True,True,HEA,3
4,Nutrition,True,True,True,NUT,3
5,Protection,True,True,True,PRO,3
6,Agriculture,True,True,False,AGR,2
7,Camp Coordination / Management,True,True,False,CCM,2
8,Coordination and support services,True,True,False,CSS,2
9,Early Recovery,True,True,False,ERY,2
10,Emergency Telecommunications,True,True,False,TEL,2
11,Logistics,True,True,False,LOG,2
12,Multi-sector,True,True,False,MS,2
13,Multipurpose Cash,True,True,False,MPC,2
14,Protection - Child Protection,True,True,False,PRO-CPN,2
15,Protection - Gender-Based Violence,True,True,False,PRO-GBV,2
16,"Protection - Housing, Land and Property",True,True,False,PRO-HLP,2
17,Protection - Mine Action,True,True,False,PRO-MIN,2
18,Water Sanitation Hygiene,True,True,False,WSH,2
19,COORDINATION AND COMMON SERVICES,False,False,True,NaN,1
20,COVID-19,False,True,False,NaN,1
21,Coordination and Support Services,False,False,True,NaN,1
22,EDUCATION,False,False,True,NaN,1
23,EMERGENCY SHELTER AND NON-FOOD ITEMS,False,False,True,NaN,1
24,FOOD SECURITY AND AGRICULTURE,False,False,True,NaN,1
25,HEALTH,False,False,True,NaN,1
26,Multi-Purpose Cash,False,False,True,NaN,1
27,Multi-Sector,False,False,True,NaN,1
28,Multiple clusters/sectors (shared),False,True,False,NaN,1
29,NUTRITION,False,False,True,NaN,1
30,Not specified,False,True,False,NaN,1
31,Other,False,True,False,NaN,1
32,PROTECTION,False,False,True,NaN,1
33,Protection - CPiE,False,False,True,NaN,1
34,Protection - GBV,False,False,True,NaN,1
35,Protection - HLP,False,False,True,NaN,1
36,Protection - Human Trafficking & Smuggling,False,True,False,NaN,1
37,"WATER, SANITATION AND HYGIENE",False,False,True,NaN,1
38,"Water, Sanitation and Hygiene",False,False,True,NaN,1